### ISSUE TITLE
error message (the application is too old)

### ISSUE THREAD

**Issue by fredsevmartins** [Open-Systems-Pharmacology/Paclitaxel-Model#3]
Hi
Please could you help me?

I am trying to open a PKsim file, but I got the message that it is a old version.
How could I open my file on PKsim 7.4 ?
Thanks  
Frederico
![Capture](https://user-images.githubusercontent.com/45317633/60574297-a5379e00-9d79-11e9-8f24-68500620040c.PNG)

**Comment by Yuri05** [comment]
You can not.
If a project file was created with a newer version of PK-Sim you must install this version (in you case version 8.0)
Latest release of the OSP Suite can always be found under http://setup.open-systems-pharmacology.org 

If for some reason you don't want an upgrade to the latest version, you can also use portable version of PK-Sim 8.0: https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/download/v8.0/pk-sim-portable-setup.zip

**Comment by fredsevmartins** [comment]
Thanks @Yuri05.
Do you have  Vancomycin in a newer (7.4) version ? 
There is one on GitHub but it PKsim 5
Many thanks

**Comment by Yuri05** [comment]
>Do you have Vancomycin in a newer (7.4) version ?
There is one on GitHub but it PKsim 5

The one on GitHub is created with PK-Sim 8.0.
Project file extension (.pksim5) has nothing to do with the project version.
